<?php


// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Github\Client();

$token = trim(file_get_contents(__DIR__ . '/.github_token'));

$client->authenticate($token, '', \Github\Client::AUTH_HTTP_TOKEN);

echo "https://github.com/settings/tokens" . PHP_EOL;

$sourceRepo = '';

$temporaryRepoName = 'shifter-temporary--'. basename(getcwd());

$gitHubRepo = $client->api('repo')->remove('amenk', $temporaryRepoName);

$gitHubRepo = $client->api('repo')->create($temporaryRepoName, 'Shifter Temporary Repo, can be deleted after shifting', $sourceRepo, false);

$sshUrl = $gitHubRepo['ssh_url'];


$repo = new \Cz\Git\GitRepository(getcwd());

$currentBranch = $repo->getCurrentBranchName();

try {
    $repo->removeRemote('shifter');
} catch(\Cz\Git\GitException $e) {
    echo "Not necessary to remove remote" . PHP_EOL;
}


$repo->addRemote('shifter', $sshUrl);

echo 'Pushing...';
$repo->push('shifter', [$currentBranch]);


echo "Go to https://laravelshift.com/shifts purchase a shift and enter the following repo name" . PHP_EOL;
echo $gitHubRepo['full_name'] . PHP_EOL;

echo "And this branch" . PHP_EOL;

echo $currentBranch;



